import type { WorkoutPlan, WorkoutTarget } from "./plans";

const reps = (value: number): WorkoutTarget => ({ kind: "repetitions", value });
const seconds = (value: number): WorkoutTarget => ({ kind: "seconds", value });

export const SCIENTIFIC_WORKOUT_PLANS: WorkoutPlan[] = [
  {
    id: "light-recovery-flow",
    name: "轻松恢复流",
    description: "低冲击唤醒全身，适合久坐后或恢复日。",
    goal: "活动度 · 轻力量 · 恢复",
    level: "入门",
    intensity: "轻",
    audience: "新手、恢复日、久坐后想活动身体的人",
    evidenceBasis: "以低强度全身活动和大肌群练习帮助建立规律运动习惯。",
    equipment: "无需器械",
    durationMinutes: 18,
    warmupSeconds: 180,
    cooldownSeconds: 180,
    transitionSeconds: 45,
    accent: "teal",
    steps: [
      { exerciseId: "chair-pose", sets: 2, target: seconds(20), restSeconds: 40 },
      { exerciseId: "knee-push-up", sets: 2, target: reps(8), restSeconds: 50 },
      { exerciseId: "glute-bridge", sets: 2, target: reps(12), restSeconds: 40 },
      { exerciseId: "bird-dog", sets: 2, target: reps(12), restSeconds: 40, note: "左右交替，共 12 次" },
      { exerciseId: "downward-dog", sets: 2, target: seconds(25), restSeconds: 30 },
    ],
  },
  {
    id: "light-lower-mobility",
    name: "轻量臀腿与平衡",
    description: "用慢速基础动作练习下肢控制和平衡。",
    goal: "臀腿激活 · 单腿稳定",
    level: "入门",
    intensity: "轻",
    audience: "想提高下肢稳定、暂不适合跳跃训练的人",
    evidenceBasis: "覆盖髋、膝、踝和单腿平衡，训练量保持保守。",
    equipment: "无需器械",
    durationMinutes: 20,
    warmupSeconds: 180,
    cooldownSeconds: 180,
    transitionSeconds: 50,
    accent: "ink",
    steps: [
      { exerciseId: "sumo-squat", sets: 2, target: reps(10), restSeconds: 50 },
      { exerciseId: "reverse-lunge", sets: 2, target: reps(10), restSeconds: 60, note: "左右交替，共 10 次" },
      { exerciseId: "calf-raise", sets: 2, target: reps(15), restSeconds: 40 },
      { exerciseId: "tree-pose", sets: 4, target: seconds(20), restSeconds: 30, note: "左右交替，每侧 2 组" },
    ],
  },
  {
    id: "light-core-reset",
    name: "轻量核心重启",
    description: "从仰卧和四点支撑开始，减少动作复杂度。",
    goal: "核心控制 · 腰盆稳定",
    level: "入门",
    intensity: "轻",
    audience: "核心训练新手、需要重建动作控制的人",
    evidenceBasis: "先练抗伸展和对侧控制，再进入短时静态支撑。",
    equipment: "无需器械",
    durationMinutes: 17,
    warmupSeconds: 150,
    cooldownSeconds: 150,
    transitionSeconds: 40,
    accent: "teal",
    steps: [
      { exerciseId: "dead-bug", sets: 2, target: reps(12), restSeconds: 40, note: "左右交替，共 12 次" },
      { exerciseId: "bird-dog", sets: 2, target: reps(12), restSeconds: 40, note: "左右交替，共 12 次" },
      { exerciseId: "plank", sets: 2, target: seconds(20), restSeconds: 50 },
      { exerciseId: "side-plank", sets: 4, target: seconds(15), restSeconds: 35, note: "左右交替，每侧 2 组" },
    ],
  },
  {
    id: "light-cardio-primer",
    name: "轻心肺入门",
    description: "短组低总量，让心率逐步上升而不过度疲劳。",
    goal: "心肺起步 · 动作协调",
    level: "入门",
    intensity: "轻",
    audience: "刚开始有氧训练、希望短时间活动的人",
    evidenceBasis: "使用可中断的短组和充足休息，便于逐步累积活动量。",
    equipment: "无需器械",
    durationMinutes: 16,
    warmupSeconds: 180,
    cooldownSeconds: 180,
    transitionSeconds: 45,
    accent: "coral",
    steps: [
      { exerciseId: "jumping-jack", sets: 3, target: reps(15), restSeconds: 45 },
      { exerciseId: "high-knees", sets: 3, target: reps(20), restSeconds: 45, note: "左右交替，共 20 次；可改为原地抬膝" },
      { exerciseId: "calf-raise", sets: 2, target: reps(15), restSeconds: 40 },
      { exerciseId: "squat", sets: 2, target: reps(10), restSeconds: 55 },
    ],
  },
  {
    id: "moderate-balanced-30",
    name: "中等全身 30 分钟",
    description: "下肢、推、核心和心肺均衡组合。",
    goal: "全身力量 · 心肺协调",
    level: "基础",
    intensity: "中",
    audience: "已掌握基础动作、每周训练 2–3 次的人",
    evidenceBasis: "覆盖主要肌群并保留动作间恢复，适合规律全身训练。",
    equipment: "无需器械",
    durationMinutes: 30,
    warmupSeconds: 240,
    cooldownSeconds: 240,
    transitionSeconds: 60,
    accent: "ink",
    steps: [
      { exerciseId: "squat", sets: 3, target: reps(12), restSeconds: 60 },
      { exerciseId: "push-up", sets: 3, target: reps(8), restSeconds: 75 },
      { exerciseId: "reverse-lunge", sets: 3, target: reps(16), restSeconds: 65, note: "左右交替，共 16 次" },
      { exerciseId: "shoulder-tap", sets: 3, target: reps(16), restSeconds: 55, note: "左右交替，共 16 次" },
      { exerciseId: "jumping-jack", sets: 3, target: reps(25), restSeconds: 45 },
    ],
  },
  {
    id: "moderate-lower-control",
    name: "中等臀腿控制",
    description: "双腿力量、侧向控制和单腿稳定依次推进。",
    goal: "臀腿力量 · 膝髋稳定",
    level: "基础",
    intensity: "中",
    audience: "希望强化臀腿和动作稳定的基础训练者",
    evidenceBasis: "双侧到单侧、矢状面到额状面，减少重复刺激。",
    equipment: "无需器械",
    durationMinutes: 31,
    warmupSeconds: 240,
    cooldownSeconds: 240,
    transitionSeconds: 65,
    accent: "coral",
    steps: [
      { exerciseId: "squat", sets: 3, target: reps(12), restSeconds: 70 },
      { exerciseId: "side-lunge", sets: 3, target: reps(14), restSeconds: 70, note: "左右交替，共 14 次" },
      { exerciseId: "reverse-lunge", sets: 3, target: reps(16), restSeconds: 75, note: "左右交替，共 16 次" },
      { exerciseId: "single-leg-deadlift", sets: 3, target: reps(12), restSeconds: 65, note: "左右交替，共 12 次" },
      { exerciseId: "calf-raise", sets: 3, target: reps(18), restSeconds: 45 },
    ],
  },
  {
    id: "moderate-dumbbell-full",
    name: "中等哑铃全身",
    description: "髋主导、蹲、推和手臂动作组成完整力量课。",
    goal: "哑铃力量 · 全身基础",
    level: "基础",
    intensity: "中",
    audience: "有一只或一对哑铃、已掌握基础器械动作的人",
    evidenceBasis: "复合动作优先，孤立动作补充；使用保留 2–3 次余力的重量。",
    equipment: "一只或一对哑铃",
    durationMinutes: 32,
    warmupSeconds: 240,
    cooldownSeconds: 240,
    transitionSeconds: 75,
    accent: "ink",
    steps: [
      { exerciseId: "goblet-squat", sets: 3, target: reps(10), restSeconds: 80 },
      { exerciseId: "dumbbell-rdl", sets: 3, target: reps(10), restSeconds: 90 },
      { exerciseId: "dumbbell-shoulder-press", sets: 3, target: reps(9), restSeconds: 85 },
      { exerciseId: "dumbbell-lateral-raise", sets: 2, target: reps(12), restSeconds: 55 },
      { exerciseId: "dumbbell-biceps-curl", sets: 2, target: reps(12), restSeconds: 55 },
    ],
  },
  {
    id: "moderate-core-cardio",
    name: "中等核心心肺",
    description: "动态核心与短有氧交替，兼顾稳定和节奏。",
    goal: "核心耐力 · 心肺节奏",
    level: "基础",
    intensity: "中",
    audience: "想在一节课中同时练核心与心肺的人",
    evidenceBasis: "动作模式交替，避免连续高冲击并保持可恢复节奏。",
    equipment: "无需器械",
    durationMinutes: 26,
    warmupSeconds: 210,
    cooldownSeconds: 210,
    transitionSeconds: 55,
    accent: "teal",
    steps: [
      { exerciseId: "mountain-climber", sets: 3, target: reps(24), restSeconds: 50, note: "左右交替，共 24 次" },
      { exerciseId: "dead-bug", sets: 3, target: reps(16), restSeconds: 45, note: "左右交替，共 16 次" },
      { exerciseId: "jumping-jack", sets: 3, target: reps(25), restSeconds: 45 },
      { exerciseId: "shoulder-tap", sets: 3, target: reps(20), restSeconds: 55, note: "左右交替，共 20 次" },
      { exerciseId: "plank", sets: 3, target: seconds(30), restSeconds: 60 },
    ],
  },
  {
    id: "high-hiit",
    name: "高强度心肺间歇",
    description: "多关节快速动作与短休息组成高强度循环。",
    goal: "心肺能力 · 全身爆发",
    level: "进阶",
    intensity: "高",
    audience: "无明显不适、已有规律训练基础的用户",
    evidenceBasis: "高强度日控制总量并安排较长动作间恢复，不建议连续多日执行。",
    equipment: "无需器械",
    durationMinutes: 24,
    warmupSeconds: 300,
    cooldownSeconds: 300,
    transitionSeconds: 75,
    accent: "coral",
    steps: [
      { exerciseId: "jumping-jack", sets: 4, target: reps(30), restSeconds: 35 },
      { exerciseId: "high-knees", sets: 4, target: reps(40), restSeconds: 40, note: "左右交替，共 40 次" },
      { exerciseId: "mountain-climber", sets: 4, target: reps(30), restSeconds: 45, note: "左右交替，共 30 次" },
      { exerciseId: "burpee", sets: 4, target: reps(8), restSeconds: 70 },
    ],
  },
  {
    id: "high-dumbbell-complex",
    name: "高强度哑铃复合",
    description: "连续复合动作提高力量耐力和全身协同。",
    goal: "力量耐力 · 代谢刺激",
    level: "进阶",
    intensity: "高",
    audience: "动作熟练、能稳定控制哑铃重量的训练者",
    evidenceBasis: "重量以全程技术稳定为先，建议保留 2 次余力。",
    equipment: "一只或一对哑铃",
    durationMinutes: 34,
    warmupSeconds: 300,
    cooldownSeconds: 300,
    transitionSeconds: 90,
    accent: "coral",
    steps: [
      { exerciseId: "dumbbell-rdl", sets: 4, target: reps(10), restSeconds: 80 },
      { exerciseId: "goblet-squat", sets: 4, target: reps(12), restSeconds: 80 },
      { exerciseId: "dumbbell-shoulder-press", sets: 4, target: reps(10), restSeconds: 85 },
      { exerciseId: "dumbbell-lateral-raise", sets: 3, target: reps(12), restSeconds: 60 },
      { exerciseId: "dumbbell-biceps-curl", sets: 3, target: reps(12), restSeconds: 60 },
    ],
  },
  {
    id: "high-bodyweight-power",
    name: "高强度徒手全身",
    description: "下肢、推和波比动作组成紧凑全身训练。",
    goal: "全身力量 · 心肺爆发",
    level: "进阶",
    intensity: "高",
    audience: "俯卧撑、弓步和波比动作均已熟练的人",
    evidenceBasis: "大肌群复合动作优先，高冲击动作前后留足恢复。",
    equipment: "无需器械",
    durationMinutes: 32,
    warmupSeconds: 300,
    cooldownSeconds: 300,
    transitionSeconds: 85,
    accent: "ink",
    steps: [
      { exerciseId: "squat", sets: 4, target: reps(15), restSeconds: 60 },
      { exerciseId: "push-up", sets: 4, target: reps(12), restSeconds: 75 },
      { exerciseId: "reverse-lunge", sets: 4, target: reps(20), restSeconds: 70, note: "左右交替，共 20 次" },
      { exerciseId: "mountain-climber", sets: 4, target: reps(30), restSeconds: 50, note: "左右交替，共 30 次" },
      { exerciseId: "burpee", sets: 3, target: reps(8), restSeconds: 80 },
    ],
  },
  {
    id: "high-core-endurance",
    name: "高强度核心耐力",
    description: "长时支撑与动态抗旋转交替，挑战躯干耐力。",
    goal: "核心耐力 · 肩髋稳定",
    level: "进阶",
    intensity: "高",
    audience: "能够稳定完成 40 秒平板支撑的训练者",
    evidenceBasis: "静态与动态核心动作交替，技术下降时应立即缩短时长。",
    equipment: "无需器械",
    durationMinutes: 28,
    warmupSeconds: 240,
    cooldownSeconds: 240,
    transitionSeconds: 70,
    accent: "teal",
    steps: [
      { exerciseId: "plank", sets: 4, target: seconds(45), restSeconds: 60 },
      { exerciseId: "shoulder-tap", sets: 4, target: reps(24), restSeconds: 55, note: "左右交替，共 24 次" },
      { exerciseId: "side-plank", sets: 6, target: seconds(25), restSeconds: 45, note: "左右交替，每侧 3 组" },
      { exerciseId: "mountain-climber", sets: 4, target: reps(30), restSeconds: 55, note: "左右交替，共 30 次" },
      { exerciseId: "dead-bug", sets: 3, target: reps(20), restSeconds: 45, note: "左右交替，共 20 次" },
    ],
  },
];

